org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
archives_base_name=nanite-library
mod_version=26.3.0.4
maven_group=dev.nanite.mods

# Common
minecraft_version=26.3
minecraft_version_range_mvn=[26.3,27)
minecraft_version_range_sem=>=26.3.0 <27.0.0
supported_minecraft_versions=26.3

# Neo
neoforge_version=26.3.0.6-beta
neoforge_version_range=[26.3.0.0,)

# Fabric
fabric_loader_version=0.19.5
fabric_api_version=0.161.0+26.3
fabric_api_version_range=>=0.161.0+26.3

# Mod options
mod_name=Nanite Library
mod_author=Nanite Team
mod_id=nanitelibrary

# Publishing
curseforge_id=1171906
modrinth_id=xSlNcCOe
github_repo=Nanite/Nanite-Library
