modLoader="javafml" #mandatory
loaderVersion="[1,)" #mandatory
license="MPL-2"

[[mods]]
modId="testneo"
version="0.0.1"
displayName="Test Neo" #mandatory
authors="Nanite Team" #optional
description='''
    Deescription
'''

[[dependencies.testneo]]
    modId="neoforge"
    required=true
    versionRange="[20.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.testneo]]
    modId="minecraft"
    required=true
    versionRange="[1.20.4,1.20.5)"
    ordering="NONE"
    side="BOTH"
